name: Python application
on: [push]
permissions:
  contents: read
jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 525600
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run:
        pip install -r requirements.txt
    - name: Run script
      env: 
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: python Discord_GWorkspace_Auth.py
